# Generated by Django 4.0 on 2024-04-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PORTFOLIO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
